name: Build
on:
  push:
    branches:
      - main
      - renovate/**
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Java
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          distribution: 'temurin'
          java-version: '22'
          java-package: 'jdk'
          cache: maven
      - name: Run mvn clean verify
        run: mvn clean verify
      - name: Publish Surefire test report
        uses: dorny/test-reporter@v1.0.0
        if: always()
        with:
          name: Surefire Tests  
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
