name: Build
on:
  push:
    branches:
      - main
      - renovate/**
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          java-package: 'jdk'
          cache: maven
      - name: Run mvn clean verify
        run: mvn clean verify
      - name: Publish Surefire test report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: always()
        with:
          name: Surefire Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
