name: Build
on:
  push:
    branches:
      - main
      - renovate/**
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: 'temurin'
          java-version: '22'
          java-package: 'jdk'
          cache: maven
      - name: Run mvn clean verify
        run: mvn clean verify
      - name: Publish Surefire test report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: always()
        with:
          name: Surefire Tests  
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
