name: main
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@3
        with:
          java-version: '21'
          cache: maven
      - run: mvn verify
