name: main
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: 'jdk'
          cache: maven
      - run: mvn clean verify
