name: main
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: 'jdk'
          cache: maven
      - run: mvn clean verify
